import { describe, it, expect } from 'vitest';
import {
	flattenTable,
	stripMdMarkups,
	stripSpaces,
	removeEmptyLines,
	mdCleanup,
} from '../../src/chunking/cleanup';

// Expected outputs in this file were generated by running the original
// Python functions from accio.ai/md-parsers.py — the port must match.

describe('flattenTable', () => {
	it('flattens a table surrounded by text', () => {
		const input =
			'before text\n\n| Col 1 | Col 2 |\n|-------|-------|\n| a     | b     |\n| c     | d     |\n\nafter text';
		// Python: 'before text\n\n\na       b\n\nc       d\nafter text'
		expect(flattenTable(input)).toBe(
			'before text\n\n\na       b\n\nc       d\nafter text',
		);
	});

	it('flattens a table at the start of the content', () => {
		const input = '| Col 1 | Col 2 |\n|-------|-------|\n| a     | b     |';
		// Python: '|\na       b\n' (leading pipe quirk preserved)
		expect(flattenTable(input)).toBe('|\na       b\n');
	});

	it('flattens multiple tables', () => {
		const input =
			'table A\n| A1 | A2 |\n|----|----|\n| 1a | 2a |\n\ntable B\n| B1 | B2 |\n|----|----|\n| 1b | 2b |\n\nend';
		// Python: 'table A\n\n1a   2a\ntable B\n\n1b   2b\nend'
		expect(flattenTable(input)).toBe(
			'table A\n\n1a   2a\ntable B\n\n1b   2b\nend',
		);
	});

	it('handles a table with no body rows', () => {
		// Python: 'text\n\n\n\n'
		expect(flattenTable('text\n| a | b |\n|---|---|\n')).toBe(
			'text\n\n\n\n',
		);
	});

	it('returns content without tables unchanged', () => {
		const input = 'just some text\nno tables here';
		expect(flattenTable(input)).toBe(input);
	});

	it('handles a table whose last line has no pipe', () => {
		// Python: '|\nx\nyz no pipe end'
		expect(flattenTable('| a | b |\n|---|---|\nxyz no pipe end')).toBe(
			'|\nx\nyz no pipe end',
		);
	});
});

describe('stripMdMarkups', () => {
	it('strips headings, emphasis, highlights, quotes, bullets, links', () => {
		const input =
			'# Title Here\n' +
			'Some **bold** and _italic_ and ==highlight== text.\n' +
			'> a quote\n' +
			'- bullet one\n' +
			'1. numbered one\n' +
			'[link text](http://example.com)\n' +
			'\n\nsecond para';
		// Python reference output:
		expect(stripMdMarkups(input)).toBe(
			'Title Here\n' +
				'Some bold and italic and highlight text.\n' +
				' a quote\n' +
				'bullet one\n' +
				'numbered one\n' +
				'link text http://example.com\n' +
				'\n\nsecond para',
		);
	});
});

describe('stripSpaces', () => {
	it('removes leading and trailing spaces per line', () => {
		expect(stripSpaces('  hello  \n\tworld\t')).toBe('hello\nworld');
	});
});

describe('removeEmptyLines', () => {
	it('collapses runs of empty lines', () => {
		expect(removeEmptyLines('a\n\n\n\nb')).toBe('a\nb');
	});
});

describe('mdCleanup', () => {
	it('cleans up markdown end to end', () => {
		const input =
			'# Title Here\n' +
			'Some **bold** and _italic_ and ==highlight== text.\n' +
			'> a quote\n' +
			'- bullet one\n' +
			'1. numbered one\n' +
			'[link text](http://example.com)\n' +
			'\n\nsecond para';
		// Python reference output:
		expect(mdCleanup(input)).toBe(
			'title here\n' +
				'some bold and italic and highlight text.\n' +
				'a quote\n' +
				'bullet one\n' +
				'numbered one\n' +
				'link text http://example.com\n' +
				'second para',
		);
	});
});
